### ISSUE TITLE
Mutation : Variables is a not a valid JSON object

### ISSUE THREAD

**Issue by quentinhayot** [aws-amplify/amplify-ios#1377]
Hi !

I'm adding my first mutation to my project and the request fails (it's not even sent) with the following error:

```console
2021-08-10 19:18:25.262474+0200 MyProject[16878:1617980] [API] Starting mutation DE7BB14B-7CE4-4D11-9661-E9EFFD836990  
Got failed event with error APIError: Variables is a not a valid JSON object
```

I spent the day on this and I'm starting to think there either is a bug or I missed something really big.
All the queries are working fine. It only happens on mutations.

The relevant part of the schema looks like this:
```yml
type File {
    id: ID!
    name: String
    type: String
    mime: String
    createdAt: AWSDateTime
    data: String
}

input FileInput {
    name: String
    type: String
    mime: String
    data: String
}

type ChatMessage {
    id: ID!
    authorName: String!
    authorIsPatient: Boolean!
    createdAt: AWSDateTime!
    body: String!
    files: [File]! 
}

input ChatMessageInput {
    body: String
    files: [FileInput]
}

    [...]

type Query {
    [...]
}

type Mutation {
    sendTcChat(message: ChatMessageInput): ChatMessage @aws_cognito_user_pools
}

schema {
    query: Query
    mutation: Mutation
}
```

I have a `GraphQLRequest` extension that looks like this:
```swift
extension GraphQLRequest {
    public static func sendTcChat(mutation: SendTcChatMutation) -> GraphQLRequest<ChatMessage> {
        let request = GraphQLRequest<ChatMessage>(document: SendTcChatMutation.operationString,
                                                  variables: mutation.variables as [String : Any],
                                                 responseType: ChatMessage.self,
                                                 decodePath: "sendTcChat")
        return request
    }
[...]
}
```

and I'm invoking the mutation like this:
```swift
private func sendTcChat() -> AnyCancellable {
        let input = ChatMessageInput(body: "Lorem ipsum", files: [])
      
        let sink = Amplify.API.mutate(request: .sendTcChat(mutation: SendTcChatMutation(message: input)))
            .resultPublisher
            .sink {
                if case let .failure(error) = $0 {
                    print("Got failed event with error \(error)") // <==== This is where the error message comes from
                }
            }
            receiveValue: { result in
                switch result {
                case .success(let message):
                    print("Got success")
                case .failure(let error):
                    print("Got failed result with \(error.errorDescription)")
                }
            }
        return sink
    }
```

Does anyone has any clue? It's driving me crazy...
